# Generated by Django 2.2.14 on 2020-07-06 06:37

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('sujet', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('message_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Appartement', 'Appartement'), ('Maison', 'Maison'), ('Bureau', 'Bureau'), ('Terrain', 'Terrain')], max_length=20)),
                ('mode', models.CharField(choices=[('A Louer', 'A Louer'), ('A Vendre', 'A Vendre')], max_length=20)),
                ('salon', models.IntegerField(default=1)),
                ('chambres', models.IntegerField(default=1)),
                ('salle_de_bain', models.IntegerField(default=1)),
                ('cuisine', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=3)),
                ('parking', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.CharField(max_length=20)),
                ('zone', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('est_disponible', models.CharField(choices=[('Disponible', 'Disponible'), ('Déjà pris', 'Déjà pris')], default='Disponible', max_length=20)),
                ('publicateur', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='properties')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='properties')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='properties')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='properties')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='properties')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='properties')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='properties')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='properties')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='properties')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='properties')),
                ('publier', models.BooleanField(default=False)),
                ('favoris', models.ManyToManyField(blank=True, related_name='favoris', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
